# Generated by Django 4.1.2 on 2022-11-05 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summaryapp', '0003_servicemodel_time_remove_assingmentmodel_service_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicemodel',
            name='description',
        ),
    ]
