# Generated by Django 4.1.2 on 2022-11-11 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('summaryapp', '0004_remove_servicemodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarberModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('age', models.DecimalField(decimal_places=0, max_digits=2)),
            ],
            options={
                'verbose_name': 'Barber',
                'verbose_name_plural': 'Barbers',
                'db_table': 'barber',
            },
        ),
        migrations.AlterField(
            model_name='assingmentmodel',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='summaryapp.barbermodel'),
        ),
    ]
