# Generated by Django 4.1.2 on 2022-11-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summaryapp', '0005_barbermodel_alter_assingmentmodel_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barbermodel',
            name='age',
        ),
    ]
